name: M10
description: gated residual FirConv
fe:
  n_block: 2
  n_channel: [128, 128]
  kernel_size: [511, 127]
  stride: [2, 8]
  window_k: [2, 9]
  residual_connection_type: 'concat'
  pooling: None #'mean'
cls:
  n_block: 2 
  n_hidden_dim: [256, 256]