name: M11
description: 2-layer FirConv with LSTM for text emotion classification with dropout
fe:
  n_block: 2
  n_channel: [128, 128]
  kernel_size: [511, 127]
  stride: [2, 8]
  window_k: [2, 9]
  residual_connection_type: channel_concat
  pooling: max
  mel_resolution: 4
  filter_type: firwin
  conv_mode: strided_conv
  norm_type: LocalResponseNorm
  complex_type: v2
seq:
  n_block: 2
  n_channel: 64
  bidirectional: False
cls:
  n_block: 2 
  n_hidden_dim: [1024, 1024]
  dropout: 0.2