name: M13
description: FirConv with fftconv
fe:
  n_block: 2
  n_channel: [64, 64]
  kernel_size: [511, 127]
  stride: [4, 4]
  groups: [1, 1]
  window_k: [2, 9]
  residual_connection_type: 'stack'
  pooling: 'mean'
  conv_type: 'firwin'
  conv_mode: 'conv'
  n_fft: False
  norm_type: 'LocalResponseNorm'
cls:
  n_block: 2 
  n_hidden_dim: [256, 256]
  norm_type: 'LayerNorm'