name: M13mfcc
description: FirConv with fftconv
mfcc:
  n_mfcc: 300
  n_fft: 1024
  hop_length: 128
  n_mels: 300
  sample_rate: 16000
pooling: 'mean'
cls:
  n_block: 2 
  n_hidden_dim: [512, 512]
  norm_type: 'LayerNorm'