name: M15_iemocap
description: FirConv sequential for iemocap
fe:
  n_block: 2
  n_channel: [64, 64]
  kernel_size: [63, 31]
  stride: [4, 4]
  window_k: [9, 9]
  residual_connection_type: 'concat'
  pooling: False
  filter_type: 'firwin'
  conv_mode: 'fftconv'
  norm_type: 'LocalResponseNorm'
seq:
  n_block: 1
  n_channel: 32
  pooling: 'max'
  use_context: True 
  bidirectional: False
cls:
  n_block: 2 
  n_hidden_dim: [128, 128]
  norm_type: 'LayerNorm'
