name: M18
description: FirConv sequential for speech emotion
fe:
  n_block: 2
  n_channel: [128, 32]
  kernel_size: [127, 63]
  stride: [2, 8]
  window_k: [2, 9] 
  mel_resolution: 4
  residual_connection_type: 'stack'
  pooling: False
  filter_type: 'firwin'
  conv_mode: 'fftconv'
  norm_type: 'LocalResponseNorm'
seq:
  n_block: 1
  n_channel: 48
  out_seq_length: 8
  use_context: False 
  bidirectional: False
cls:
  n_block: 2 
  n_hidden_dim: [512, 512]
  norm_type: 'LayerNorm'
  dropout: 0.15
