name: M20
description: FirConv + LSTM
fe:
  n_block: 1
  n_channel: [256]
  kernel_size: [511]
  stride: [2]
  window_k: [2] 
  # residual_connection_type: concat
  # pooling: mean
  filter_type: sinc
  learnable_bands: False
  learnable_windows: True
  shared_window: True
  window_func: hamming
  mel_resolution: 3
  conv_mode: conv
  norm_type: LocalResponseNorm
seq:
  n_block: 1
  n_channel: 48
  out_seq_length: 8
  use_context: False 
  bidirectional: False
cls:
  n_block: 2 
  n_hidden_dim: [512, 512]
  norm_type: 'LayerNorm'
  dropout: 0.15