name: M12_debug
description: FirConv sequential for iemocap
fe:
  n_block: 2
  n_channel: [64, 32]
  kernel_size: [63, 31]
  stride: [4, 16]
  window_k: [9, 9]
  residual_connection_type: 'stack'
  pooling: False
  filter_type: 'firwin'
  conv_mode: 'fftconv'
  norm_type: 'LocalResponseNorm'
seq:
  seq_type: 'mamba' # lstm
  d_state: 2  # SSM state expansion factor
  d_conv: 4    # Local convolution width
  expand: 2
  n_block: 1
  n_channel: 97
  pooling: 'mean'
cls:
  n_block: 2 
  n_hidden_dim: [128, 128]
  norm_type: 'LayerNorm'
