name: torch dry run
batch_size: 16
early_stopping: False
accumulate_grad: False
optimizer: RAdam
optimizer_kwargs:
  weight_decay: 0.0001
learning_rate_init: 0.001
lr_scheduler: OneCyleLR
lr_scheduler_kwargs:
  step_size: 40
max_epochs: 5
min_epochs: 1
detect_anomaly: True
accelerator: cpu
num_nodes: 1
devices: 1
num_workers: 8
val_check_interval: 0.5
precision: 32
cross_validation: False
num_folds: 5
random_seed: 42 