name: torch dry run
batch_size: 8
early_stopping: False
optimizer: RAdam
optimizer_kwargs:
  weight_decay: 0.0001
learning_rate_init: 0.001
lr_scheduler: OneCyleLR
lr_scheduler_kwargs:
  step_size: 40
max_epochs: 10
min_epochs: 2
accelerator: gpu
devices: 1
num_workers: 8
val_check_interval: 0.5
precision: 16-mixed
cross_validation: False
num_folds: 5
random_seed: 42 