dataset: ravdess
num_class: 4
classnames: ["neutral", "happy", "sad", "angry"]
use_label: label_emotion_key
use_classnames: ["neu", "hap", "sad", "ang"] # only effective when cv_prediction=True
use_all_data: False
experiment: muser_nopca
projector_type: False
n_components: 0.125 # int number; or percentage of components to keep (make sure fit=True in dataloader)
scaler_type: False # scale mel, cqt, chroma but not mfcc
cv_prediction: False # run cv based on the split, and return prediction on the whole dataset. If True, ignore the next 3 params
cross_validation: False # number_of_fold or False
n_repeats: 1
test_size: 0.2

features:
  - audio16k
feature_list: False

models:
  - M9

train: 
  batch_size: 32
  optimizer: 'adam'
  learning_rate_scheduler: 'adaptive'
  learning_rate_init: 0.001
  l2_reg: 0.001
  n_epoch: 500
  early_stopping: False
