name: heartsound
dataset_class: SplittedWaveformDataset
root: heartsound/
audio_dir: full_release/
feature_dir: fold1/
label_name: labels_binary
feature_name: audio16k
num_classes: 2
label_values: [0, 1]
classnames: [murmur, normal]
target_labels: [murmur, normal]