name: meld
dataset_class: WaveformDataset
root: meld/
audio_dir: full_release/
feature_dir: features_4balanced/
label_name: label_emotion # label4
feature_name: audio16k
num_classes: 4
label_values: [0, 1, 2, 3] # [neu, hap, sad, ang]
classnames: [neu, hap, sad, ang]
target_labels: [ang, neu, sad, hap]