name: msp_podcast
root: msp_podcast/
audio_dir: full_release/
feature_dir: features_4balanced/
label_name: label_emotion
feature_name: audio16k
num_classes: 4
label_values: [anger, neutral, sadness, happiness]
classnames: [ang, neu, sad, hap]
target_labels: [ang, neu, sad, hap]