name: ravdess
config_type: dataset
root: ../data/ravdess/
audio: ../data/ravdess/audio16k
preprocessed: ../data/ravdess/features/
classnames: [neutral, calm, happy, sad, angry, fearful, disgust, surprised]
tasks:
  8_emotions:
    labels: [0, 1, 2, 3, 4, 5, 6, 7]
    classnames: [neutral, calm, happy, sad, angry, fearful, disgust, surprised]
    colors: [black, grey, green, blue, red, purple, orange, lime]
    markers: [o, o, ^, s, s, s, s, ^]
  4_emotions:
    labels: [0, 2, 3, 4]
    classnames: [neutral, happy, sad, angry]
    colors: [gray, green, blue, red]
    markers: [o, ^, s, s]