name: text_emotion
dataset_class: SplittedWaveformDataset
root: text_emotion/
audio_dir: full_release/
feature_dir: preprocessing/
label_name: labels_13emotions
feature_name: signals_3channels_win5stride1
num_classes: 13
label_values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
classnames: ['anger', 'boredom', 'empty', 'enthusiasm', 'fun', 'happiness', 'hate', 'love', 'neutral', 'relief', 'sadness', 'surprise', 'worry']
target_labels:  ['anger', 'boredom', 'empty', 'enthusiasm', 'fun', 'happiness', 'hate', 'love', 'neutral', 'relief', 'sadness', 'surprise', 'worry']